// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkOMzhXtFSP9N4uA7z-VRKAUK-ac8GfBc',
    appId: '1:791471197513:web:44309e824ad6ed653f5e98',
    messagingSenderId: '791471197513',
    projectId: 'matcha-notes-77bf5',
    authDomain: 'matcha-notes-77bf5.firebaseapp.com',
    storageBucket: 'matcha-notes-77bf5.appspot.com',
    measurementId: 'G-Y4SMRHE32X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv-78cZwb1yp9jFsyra_Hf_ybxMtGz1XM',
    appId: '1:791471197513:android:83887abb69a36fad3f5e98',
    messagingSenderId: '791471197513',
    projectId: 'matcha-notes-77bf5',
    storageBucket: 'matcha-notes-77bf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0TceG6lespXLHQiosUA6qI25JeWs-wVA',
    appId: '1:791471197513:ios:12c4bcfc5331987f3f5e98',
    messagingSenderId: '791471197513',
    projectId: 'matcha-notes-77bf5',
    storageBucket: 'matcha-notes-77bf5.appspot.com',
    iosBundleId: 'com.example.matchaNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0TceG6lespXLHQiosUA6qI25JeWs-wVA',
    appId: '1:791471197513:ios:9c945c8017651ad93f5e98',
    messagingSenderId: '791471197513',
    projectId: 'matcha-notes-77bf5',
    storageBucket: 'matcha-notes-77bf5.appspot.com',
    iosBundleId: 'com.example.matchaNotes.RunnerTests',
  );
}
